//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_Seminario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BLOG_SEMINARIOEntities : DbContext
    {
        public BLOG_SEMINARIOEntities()
            : base("name=BLOG_SEMINARIOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIAS> CATEGORIAS { get; set; }
        public virtual DbSet<POST> POST { get; set; }
        public virtual DbSet<SUB_CATEGORIA> SUB_CATEGORIA { get; set; }
        public virtual DbSet<VINCULO_POST> VINCULO_POST { get; set; }
        public virtual DbSet<IMAGEN_POST> IMAGEN_POST { get; set; }
    }
}
