//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_Seminario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POST()
        {
            this.IMAGEN_POST = new HashSet<IMAGEN_POST>();
            this.VINCULO_POST = new HashSet<VINCULO_POST>();
        }
    
        public int ID_POST { get; set; }
        public string TITULO { get; set; }
        public string NOTA_POST { get; set; }
        public Nullable<bool> STATUS_POST { get; set; }
        public Nullable<int> CATEGORIA { get; set; }
        public Nullable<int> SUBCATEGORIA { get; set; }
    
        public virtual CATEGORIAS CATEGORIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGEN_POST> IMAGEN_POST { get; set; }
        public virtual SUB_CATEGORIA SUB_CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VINCULO_POST> VINCULO_POST { get; set; }
    }
}
