CREATE TABLE CATEGORIAS (
ID_CATEGORIA INT IDENTITY(1,1) PRIMARY KEY, 
NOMBRE_CATEGORIA VARCHAR(125) NOT NULL
);

CREATE TABLE SUB_CATEGORIA (
ID_CATEGORIA INT FOREIGN KEY REFERENCES CATEGORIAS (ID_CATEGORIA),
ID_SUB_CATEGORIA INT IDENTITY(1,1), 
NOMBRE_CATEGORIA VARCHAR(125) NOT NULL,
PRIMARY KEY (ID_SUB_CATEGORIA)
);

CREATE TABLE POST (
ID_POST INT IDENTITY(1,1) PRIMARY KEY, 
TITULO VARCHAR(150) NOT NULL, 
NOTA_POST VARCHAR(MAX),
STATUS_POST BIT,
CATEGORIA INT FOREIGN KEY REFERENCES CATEGORIAS (ID_CATEGORIA), 
SUBCATEGORIA INT FOREIGN KEY REFERENCES SUB_CATEGORIA (ID_SUB_CATEGORIA)
);

CREATE TABLE VINCULO_POST (
ID_VINCULO INT IDENTITY(1,1), 
ID_POST INT FOREIGN KEY REFERENCES POST(ID_POST),
ENLACE VARCHAR(750) NOT NULL,
DESCRIPCION_BOTON_ENLACE VARCHAR(50) NOT NULL,
PRIMARY KEY (ID_VINCULO,ID_POST)
);

CREATE TABLE IMAGEN_POST (
ID_IMAGEN INT IDENTITY(1,1), 
ID_POST INT FOREIGN KEY REFERENCES POST(ID_POST),
LINK_IMAGEN VARCHAR(350) NOT NULL
);

